[package]
name = "native-launcher"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
combine-game = { package = "combine-game", path = "../.." }
bevy = "0.8"
image = "0.24.3"
winit = "0.26.1"
